### PR TITLE
Update Default Props

### PR DESCRIPTION
**Pull request by gawasvedraj**
As the sailfish prop is banned

### CODE REVIEW

**Comment by osm0sis** [comment]
If you're going to use a beta print then you should use the newest. They expire 5-6 weeks after the beta's release date. That's also why they're not really suitable at all for the hardcoded default.

**Comment by pershoot** [comment]
My two cents; the ownness should be on the user to update said prints, on-device.  Constantly updating source to bundle these item(s) may become daunting, amongst other issue(s) such as bringing wider attention to them.

**Comment by osm0sis** [comment]
Agreed, if anything it should probably go back to being the original RCS-banned sailfish print, which will unfortunately fail on sw keybox (needs api_level prop, as demonstrated in my open issue), but can pass strong with unrevoked hw keybox.

Then people can just take their hint from the README example to keep updating to the latest Pixel beta print.

That or it's time to gut the spoof_build_vars feature out of TS entirely so that people can use PIFork for the print part instead. I'll be releasing v10 with the needed Advanced Settings for Strong with TS as soon as I get the chance to do the documentation. Currently available in CI however.

**Comment by gawasvedraj** [comment]
> That or it's time to gut the spoof_build_vars feature out of TS entirely so that people can use PIFork for the print part instead.

Agree. It would be good to have a modular approach. Also that means we can completely strip out zygisk from TS.

**Pull request closed without merging**
