### PR TITLE
Refine spoof build vars

### PR DESCRIPTION
**Pull request by yujincheng08**

### CODE REVIEW

**Comment by osm0sis** [comment]
Good idea going for spoof_build_vars.prop instead of .json. 👍

Could you please consider moving SECURITY_PATCH to the bottom of the struct/defaults after TAGS so that the order matches the uninterrupted contents of the FINGERPRINT value?

E.g.
```
MANUFACTURER=Google
MODEL=Pixel 8 Pro
FINGERPRINT=google/husky/husky:14/AP1A.240505.005/11677807:user/release-keys
BRAND=google
PRODUCT=husky
DEVICE=husky
RELEASE=14
ID=AP1A.240505.005
INCREMENTAL=11677807
TYPE=user
TAGS=release-keys
SECURITY_PATCH=2024-05-05
```

Thanks!

**Comment by chiteroman** [comment]
With this CMake arguments I can compile on Android Studio. Also you forgot to disable rtti and exceptions :(

```
cmake {
    arguments += arrayOf(
        "-DANDROID_STL=none",
        "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON",
        "-DANDROID_CPP_FEATURES=no-rtti no-exceptions",
        "-DCMAKE_BUILD_TYPE=MinSizeRel",
        "-DCMAKE_CXX_STANDARD=23",
        "-DCMAKE_C_STANDARD=23",
        "-DCMAKE_VISIBILITY_INLINES_HIDDEN=ON",
        "-DCMAKE_CXX_VISIBILITY_PRESET=hidden",
        "-DCMAKE_C_VISIBILITY_PRESET=hidden",
    )
}
```

**Comment by aviraxp** [comment]
release strings in 2nd patch

**Comment by aviraxp** [comment]
> With this CMake arguments I can compile on Android Studio. Also you forgot to disable rtti and exceptions :(
> 
> ```
> cmake {
>     arguments += arrayOf(
>         "-DANDROID_STL=none",
>         "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON",
>         "-DANDROID_CPP_FEATURES=no-rtti no-exceptions",
>         "-DCMAKE_BUILD_TYPE=MinSizeRel",
>         "-DCMAKE_CXX_STANDARD=23",
>         "-DCMAKE_C_STANDARD=23",
>         "-DCMAKE_VISIBILITY_INLINES_HIDDEN=ON",
>         "-DCMAKE_CXX_VISIBILITY_PRESET=hidden",
>         "-DCMAKE_C_VISIBILITY_PRESET=hidden",
>     )
> }
> ```

Update to latest as canary?

**Comment by osm0sis** [comment]
The default entries never seem to get dumped anymore after the spoof_build_vars file gets created, even after a reboot:
https://github.com/5ec1cff/TrickyStore/commit/9be33d95284f35e793f9bdfe1679eb0d8963e2a9#diff-483371e34164bb32c0416a5224d0d5d9e904a3473640a9e634bf893b8d6c36bdR207-R220

**Comment by aviraxp** [comment]
fixed with latest commit

**Comment by osm0sis** [comment]
Thanks!

**Pull request merged**
