### PR TITLE
Update customize.sh

### PR DESCRIPTION
**Pull request by VisionR1**
I decided to add this lines (thanks @aviraxp for the idea), according to this post on XDA, for better understood.
Post

### CODE REVIEW

**Comment by 5ec1cff** [comment]
The folder will be created automatically on first boot

**Comment by 5ec1cff** [comment]
https://github.com/5ec1cff/TrickyStore/blob/49554a8bbdc2011b5e1941fd66b07a98bb306701/service/src/main/java/io/github/a13e300/tricky_store/Config.kt#L61

**Comment by VisionR1** [comment]
Thanks for info.
Just I try it and after reboot, still folder not create.

**Comment by VisionR1** [comment]
> It's not created on my stock ROM Pixel 8 Pro either. I'm on Magisk Canary Debug 27004 with Shamiko 1.1(344). So @VisionR1, this should be an open Issue not a PR.

Thanks you.
Yeah, because and other users have the same, it seem like issue.
Just I try to help for that I open this.

**Pull request closed without merging**
